spring.application.name=Movie_Ticket_Booking_System
spring.datasource.initialize=false

# ===============================
# CONFIG H2 DATABASE (IN-MEMORY)
# ===============================
spring.datasource.url=jdbc:h2:mem:movie_booking_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# CONFIG HIBERNATE / JPA
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.session.store-type=none

# ===============================
# SECURITY JWT CONFIG
# ===============================
jwt.secret=9a72635c6e8346e29a672348a8bcfd7612345678901234567890123456789012
jwt.expiration=86400
jwt.expires-in=86400

logging.level.org.springframework.security=DEBUG