spring.application.name=Movie_Ticket_Booking_System
spring.datasource.initialize=false

# ===============================
# CONNECTION CONFIG DATABASE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/movie_booking_db
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIG HIBERNATE / JPA
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=local

spring.session.store-type=none

logging.level.org.springframework.security=DEBUG